### ISSUE TITLE
Banner displays default "Information coming soon" description if the banner custom post is blank/empty

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Homeart-Building-Group#6]
![image](https://cloud.githubusercontent.com/assets/12888048/9712883/6bf20896-5580-11e5-9961-91c1e6a85810.png)
![image](https://cloud.githubusercontent.com/assets/12888048/9712888/6e6d2b46-5580-11e5-83a6-ca09ece19db7.png)

**Comment by ramoncebudigital** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/11186436/9751731/e2148ab6-56da-11e5-8741-2cf4d955b0b8.png)

**Comment by romatitan** [comment]
Yes, use "Information Coming soon" instead of Lorem text.
But still, It should not be a default text for the description if the custom post is blank or empty.

**Comment by christiancebudigital** [comment]
Hi Roma,

We don't think this is a bug, what we think is that, we don't want our content to have empty content right?,so that is why we set the content as default text to "Information coming soon", anyways you can also add "Information coming soon" in page description backend, if you feel that it is not right, let me know your thoughts.

Thanks,
Christian

**Comment by bernardtitan** [comment]
We can't assume content for clients. If there is nothing inputted in the backend, there shouldn't be anything displayed either.
